FROM arm64v8/alpine:3.16.3 AS base
WORKDIR /opt/app

FROM base AS build
RUN apk add alpine-sdk ncurses-dev
COPY . .
RUN make

FROM base
RUN apk add ncurses
COPY --from=build /opt/app/zork ./
COPY dtextc.dat .

CMD /opt/app/zork